// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package lfu

import (
	"sync"

	"github.com/dsh2dsh/go-tinylfu"
)

// Ensure that moqBackend does implement backend.
// If this is not the case, regenerate this file with mockery.
var _ backend = &moqBackend{}

// moqBackend is a mock implementation of backend.
//
//	func TestSomethingThatUsesbackend(t *testing.T) {
//
//		// make and configure a mocked backend
//		mockedbackend := &moqBackend{
//			DelFunc: func(key string)  {
//				panic("mock out the Del method")
//			},
//			GetFunc: func(key string) ([]byte, bool) {
//				panic("mock out the Get method")
//			},
//			SetFunc: func(item *tinylfu.Item[[]byte])  {
//				panic("mock out the Set method")
//			},
//		}
//
//		// use mockedbackend in code that requires backend
//		// and then make assertions.
//
//	}
type moqBackend struct {
	// DelFunc mocks the Del method.
	DelFunc func(key string)

	// GetFunc mocks the Get method.
	GetFunc func(key string) ([]byte, bool)

	// SetFunc mocks the Set method.
	SetFunc func(item *tinylfu.Item[[]byte])

	// calls tracks calls to the methods.
	calls struct {
		// Del holds details about calls to the Del method.
		Del []struct {
			// Key is the key argument value.
			Key string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Key is the key argument value.
			Key string
		}
		// Set holds details about calls to the Set method.
		Set []struct {
			// Item is the item argument value.
			Item *tinylfu.Item[[]byte]
		}
	}
	lockDel sync.RWMutex
	lockGet sync.RWMutex
	lockSet sync.RWMutex
}

// Del calls DelFunc.
func (mock *moqBackend) Del(key string) {
	if mock.DelFunc == nil {
		panic("moqBackend.DelFunc: method is nil but backend.Del was just called")
	}
	callInfo := struct {
		Key string
	}{
		Key: key,
	}
	mock.lockDel.Lock()
	mock.calls.Del = append(mock.calls.Del, callInfo)
	mock.lockDel.Unlock()
	mock.DelFunc(key)
}

// DelCalls gets all the calls that were made to Del.
// Check the length with:
//
//	len(mockedbackend.DelCalls())
func (mock *moqBackend) DelCalls() []struct {
	Key string
} {
	var calls []struct {
		Key string
	}
	mock.lockDel.RLock()
	calls = mock.calls.Del
	mock.lockDel.RUnlock()
	return calls
}

// ResetDelCalls reset all the calls that were made to Del.
func (mock *moqBackend) ResetDelCalls() {
	mock.lockDel.Lock()
	mock.calls.Del = nil
	mock.lockDel.Unlock()
}

// Get calls GetFunc.
func (mock *moqBackend) Get(key string) ([]byte, bool) {
	if mock.GetFunc == nil {
		panic("moqBackend.GetFunc: method is nil but backend.Get was just called")
	}
	callInfo := struct {
		Key string
	}{
		Key: key,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(key)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedbackend.GetCalls())
func (mock *moqBackend) GetCalls() []struct {
	Key string
} {
	var calls []struct {
		Key string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// ResetGetCalls reset all the calls that were made to Get.
func (mock *moqBackend) ResetGetCalls() {
	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()
}

// Set calls SetFunc.
func (mock *moqBackend) Set(item *tinylfu.Item[[]byte]) {
	if mock.SetFunc == nil {
		panic("moqBackend.SetFunc: method is nil but backend.Set was just called")
	}
	callInfo := struct {
		Item *tinylfu.Item[[]byte]
	}{
		Item: item,
	}
	mock.lockSet.Lock()
	mock.calls.Set = append(mock.calls.Set, callInfo)
	mock.lockSet.Unlock()
	mock.SetFunc(item)
}

// SetCalls gets all the calls that were made to Set.
// Check the length with:
//
//	len(mockedbackend.SetCalls())
func (mock *moqBackend) SetCalls() []struct {
	Item *tinylfu.Item[[]byte]
} {
	var calls []struct {
		Item *tinylfu.Item[[]byte]
	}
	mock.lockSet.RLock()
	calls = mock.calls.Set
	mock.lockSet.RUnlock()
	return calls
}

// ResetSetCalls reset all the calls that were made to Set.
func (mock *moqBackend) ResetSetCalls() {
	mock.lockSet.Lock()
	mock.calls.Set = nil
	mock.lockSet.Unlock()
}

// ResetCalls reset all the calls that were made to all mocked methods.
func (mock *moqBackend) ResetCalls() {
	mock.lockDel.Lock()
	mock.calls.Del = nil
	mock.lockDel.Unlock()

	mock.lockGet.Lock()
	mock.calls.Get = nil
	mock.lockGet.Unlock()

	mock.lockSet.Lock()
	mock.calls.Set = nil
	mock.lockSet.Unlock()
}
